/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Segment Meta
         * @description What each customer group means.
         *
         *     The rules live in `agents/_segments.py`; the UI shows them as tooltips
         *     rather than restating them, so the two cannot drift apart.
         */
        get: operations["segment_meta_meta_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/new-idea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Idea Run
         * @description Start a launch plan. Returns immediately; follow /events for progress.
         */
        post: operations["create_new_idea_run_runs_new_idea_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Clarifying Questions */
        post: operations["answer_clarifying_questions_runs__run_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/existing-business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Business Review Run */
        post: operations["create_business_review_run_runs_existing_business_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Everything the UI needs to render a run, in one request.
         */
        get: operations["get_run_detail_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Events
         * @description Plain polling, for clients that would rather not hold a stream open.
         */
        get: operations["get_run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description Server-sent events, resumable from `after_seq`.
         *
         *     The client sends the last sequence number it saw, so a reload replays
         *     what it missed rather than restarting the run's progress from nothing.
         */
        get: operations["stream_run_events_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Usage
         * @description Tokens, calls and cache hits for this run.
         *
         *     `settle=true` waits for litellm's background thread to finish reporting;
         *     only worth it right after a run ends.
         */
        get: operations["get_run_usage_runs__run_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/landing-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Landing Page
         * @description The one-page launch site built from this run's plan.
         */
        get: operations["get_landing_page_runs__run_id__landing_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Orders
         * @description Parse an uploaded order history and report what was found.
         *
         *     The founder sees the result before committing, including how many rows had
         *     to be skipped -- which is their signal that the wrong column was matched.
         */
        post: operations["preview_orders_orders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/sample.{extension}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample Orders
         * @description A realistic order file, for a founder who wants to try the flow.
         */
        get: operations["sample_orders_orders_sample__extension__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswersRequest
         * @description The founder's replies, keyed by the question they answer.
         */
        AnswersRequest: {
            /** Answers */
            answers?: {
                [key: string]: string;
            };
        };
        /** Body_preview_orders_orders_preview_post */
        Body_preview_orders_orders_preview_post: {
            /** File */
            file: string;
        };
        /** EventOut */
        EventOut: {
            /** Seq */
            seq: number;
            /** Run Id */
            run_id: number;
            /** Kind */
            kind: string;
            /** Agent */
            agent: string | null;
            /** Message */
            message: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string | null;
        };
        /** ExistingBusinessRequest */
        ExistingBusinessRequest: {
            /** Description */
            description: string;
            /**
             * Currency
             * @description One of INR, USD, EUR, GBP
             * @default INR
             */
            currency: string;
            metrics: components["schemas"]["PeriodMetricsIn"];
            /**
             * Budget
             * @description What the founder can deploy next period
             */
            budget: number;
            /**
             * Include Funding
             * @default true
             */
            include_funding: boolean;
            /** Orders Token */
            orders_token?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewIdeaRequest */
        NewIdeaRequest: {
            /**
             * Pitch
             * @description What the founder wants to build
             */
            pitch: string;
            /**
             * Currency
             * @description One of INR, USD, EUR, GBP
             * @default INR
             */
            currency: string;
            /**
             * Starting Capital
             * @description Capital available for the launch
             */
            starting_capital: number;
            /** Monthly Fixed Costs */
            monthly_fixed_costs?: number | null;
            /** Unit Cost */
            unit_cost?: number | null;
            /**
             * Runway Months
             * @default 6
             */
            runway_months: number;
            /**
             * Include Formation
             * @default true
             */
            include_formation: boolean;
            /**
             * Include Funding
             * @default true
             */
            include_funding: boolean;
        };
        /**
         * OrdersPreview
         * @description What the founder sees before committing to an upload.
         *
         *     A parsed preview rather than a bare "file accepted": order files are messy
         *     exports, and the number of rows that had to be skipped is the founder's
         *     signal that the wrong column was picked up.
         */
        OrdersPreview: {
            /** Token */
            token: string;
            /** Rows */
            rows: number;
            /** Skipped Rows */
            skipped_rows: number;
            /** Customers */
            customers: number;
            /** First Order */
            first_order: string | null;
            /** Last Order */
            last_order: string | null;
            /** Columns */
            columns: string[];
        };
        /** PeriodMetricsIn */
        PeriodMetricsIn: {
            /**
             * Period Label
             * @description e.g. "FY2025-26"
             */
            period_label: string;
            /** Revenue */
            revenue: number;
            /**
             * Net Profit
             * @description Negative for a loss
             */
            net_profit: number;
            /** Total Debt */
            total_debt: number;
            /**
             * Period Months
             * @default 12
             */
            period_months: number;
            /** Ebitda */
            ebitda?: number | null;
            /** Cash In Bank */
            cash_in_bank?: number | null;
            /** Marketing Spend */
            marketing_spend?: number | null;
            /** New Customers */
            new_customers?: number | null;
            /** Customers At Start */
            customers_at_start?: number | null;
            /** Customers Lost */
            customers_lost?: number | null;
        };
        /** RecordOut */
        RecordOut: {
            /** Id */
            id: number;
            /** Cycle */
            cycle: number;
            /** Agent */
            agent: string;
            /** Input Snapshot */
            input_snapshot: {
                [key: string]: unknown;
            };
            /** Decision */
            decision: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: string;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: number;
            /** Status */
            status: string;
        };
        /** RunDetail */
        RunDetail: {
            run: components["schemas"]["RunSummary"];
            /** Records */
            records: components["schemas"]["RecordOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: number;
            /** Workspace Id */
            workspace_id: number;
            /** Mode */
            mode: string | null;
            /** Label */
            label: string | null;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** UsageAgent */
        UsageAgent: {
            /** Agent */
            agent: string;
            /** Calls */
            calls: number;
            /** Cache Hits */
            cache_hits: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Seconds */
            seconds: number;
        };
        /** UsageOut */
        UsageOut: {
            /** Agents */
            agents: components["schemas"]["UsageAgent"][];
            /** Totals */
            totals: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    segment_meta_meta_segments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_idea_run_runs_new_idea_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewIdeaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_clarifying_questions_runs__run_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_business_review_run_runs_existing_business_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExistingBusinessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_runs__run_id__get: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_runs__run_id__stream_get: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_usage_runs__run_id__usage_get: {
        parameters: {
            query?: {
                settle?: boolean;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_landing_page_runs__run_id__landing_page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_orders_orders_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_orders_orders_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_orders_orders_sample__extension__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                extension: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
