"""Analytics agent — aggregates simulator + execution output into KPIs and a
natural-language summary that becomes next cycle's Strategy input, closing
the loop.

Numeric aggregation is plain Python (deterministic, no LLM needed). The
narrative summary is generated by a Google ADK LlmAgent with per-run
session memory, so cross-cycle trend commentary is possible instead of
single-cycle snapshots.

Backed by Groq (via LiteLlm), not Gemini directly -- see strategy.py for
why (Gemini's free-tier 20 req/day cap).
"""

import asyncio
from dataclasses import dataclass

from google.adk import Runner
from google.adk.agents import LlmAgent
from google.adk.models.lite_llm import LiteLlm
from google.adk.sessions import InMemorySessionService
from google.genai import types

from agents._retry import retry_on_rate_limit
from simulator.market_simulator import SimulationResult

APP_NAME = "flywheel"
USER_ID = "flywheel_run"
DEFAULT_MODEL = "groq/qwen/qwen3.8-27b"

_INSTRUCTION = """You are the Analytics agent for Flywheel, a simulated startup run as
closed-loop plan -> fund -> execute -> measure -> revise cycles.

Each cycle you're given this cycle's KPIs (revenue, conversion rate, CAC, churn, any
market shock). Write a 2-3 sentence natural-language summary for the Strategy agent to
read next cycle. Reference how this cycle compares to prior cycles when you have that
history in this conversation, and call out anything that should change strategy. Do not
just restate every number -- highlight what matters."""


@dataclass
class AnalyticsReport:
    cycle: int
    revenue: float
    conversion_rate: float
    cac: float
    churn_rate: float
    summary: str


class AnalyticsAgent:
    """Google ADK LlmAgent for the narrative summary; numeric KPI
    aggregation below is plain Python and deterministic on purpose."""

    def __init__(self, model: str = DEFAULT_MODEL, session_id: str = "analytics_session"):
        resolved_model = LiteLlm(model=model) if model.startswith("groq/") else model
        self._agent = LlmAgent(name="analytics_agent", model=resolved_model, instruction=_INSTRUCTION)
        self._session_service = InMemorySessionService()
        self._runner = Runner(agent=self._agent, app_name=APP_NAME, session_service=self._session_service)
        self._session_id = session_id
        self._session_ready = False

    async def _ensure_session(self):
        if not self._session_ready:
            await self._session_service.create_session(
                app_name=APP_NAME, user_id=USER_ID, session_id=self._session_id
            )
            self._session_ready = True

    async def _summarize_async(self, cycle: int, sim_result: SimulationResult, leads: int) -> AnalyticsReport:
        await self._ensure_session()

        conversion_rate = (sim_result.conversions / leads) if leads else 0.0
        kpi_text = (
            f"Cycle {cycle} KPIs -- revenue: ${sim_result.revenue:.2f}, "
            f"conversions: {sim_result.conversions} from {leads} leads "
            f"({conversion_rate:.1%} conversion), CAC: ${sim_result.cac:.2f}, "
            f"churn: {sim_result.churn_rate:.1%}."
        )
        if sim_result.shock_applied:
            kpi_text += f" Market shock this cycle: {sim_result.shock_applied}."

        content = types.Content(role="user", parts=[types.Part(text=kpi_text)])

        summary = None
        async for event in self._runner.run_async(user_id=USER_ID, session_id=self._session_id, new_message=content):
            if event.is_final_response() and event.content and event.content.parts:
                summary = event.content.parts[0].text

        if summary is None:
            raise RuntimeError("Analytics agent produced no response")

        return AnalyticsReport(
            cycle=cycle,
            revenue=sim_result.revenue,
            conversion_rate=round(conversion_rate, 4),
            cac=sim_result.cac,
            churn_rate=sim_result.churn_rate,
            summary=summary.strip(),
        )

    @retry_on_rate_limit()
    def summarize(self, cycle: int, sim_result: SimulationResult, leads: int) -> AnalyticsReport:
        return asyncio.run(self._summarize_async(cycle, sim_result, leads))
